# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarm', '0003_auto_20180221_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latch', models.CharField(choices=[('0', 'Disabled'), ('1', 'Enabled')], default='0', max_length=2)),
                ('gwID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alarm.gateways')),
            ],
        ),
        migrations.CreateModel(
            name='CareRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.date.today)),
                ('end_time', models.TimeField(default=datetime.date.today)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.sensors')),
            ],
        ),
    ]
