# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerule',
            name='in_rule',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
