# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='action_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submission time')),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraMac', models.CharField(max_length=17)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('securityStatus', models.CharField(max_length=10)),
                ('lastSeenTimestamp', models.DateTimeField(verbose_name='Submission time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='file_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submission time')),
                ('filename', models.CharField(max_length=100)),
                ('cameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebaseKey', models.CharField(max_length=153)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submission time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action_list',
            name='cameraID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera'),
        ),
    ]
