# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='lastSeenTimestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission time'),
        ),
    ]
