# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20170402_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action_list',
            old_name='cameraID',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='file_list',
            old_name='cameraID',
            new_name='camera',
        ),
    ]
