# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20170409_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_list',
            name='action',
            field=models.CharField(max_length=200),
        ),
    ]
