# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20170526_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submission time')),
                ('sensor_type', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
        ),
    ]
