# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
